// DO NOT EDIT THIS FILE DIRECTLY!
// This file was automatically generated by `generate_dope_interfaces.py`

#ifndef DOPEY_NOT_INCLUDED_DIRECTLY
#error "dope_generated_type_identifier_traits.hpp should not be included directly"
#endif

template<typename T>
struct type_identifier {};

template<>
struct type_identifier<int> {
  constexpr static CFI_type_t value = CFI_type_int;
};

template<>
struct type_identifier<float> {
  constexpr static CFI_type_t value = CFI_type_float;
};

template<>
struct type_identifier<double> {
  constexpr static CFI_type_t value = CFI_type_double;
};

template<>
struct type_identifier<bool> {
  constexpr static CFI_type_t value = CFI_type_Bool;
};

template<typename T>
constexpr static auto type_identifier_v = type_identifier<T>::value;

