! DO NOT EDIT THIS FILE DIRECTLY!
! This file was automatically generated by `generate_dope_interfaces.py`

module procedure :: make_dope_1d_c_bool
module procedure :: make_dope_1d_c_int
module procedure :: make_dope_1d_c_float
module procedure :: make_dope_1d_c_double
module procedure :: make_dope_2d_c_bool
module procedure :: make_dope_2d_c_int
module procedure :: make_dope_2d_c_float
module procedure :: make_dope_2d_c_double
module procedure :: make_dope_3d_c_bool
module procedure :: make_dope_3d_c_int
module procedure :: make_dope_3d_c_float
module procedure :: make_dope_3d_c_double
