#define COMMENT DO NOT EDIT THIS FILE DIRECTLY!
#undef COMMENT
#define COMMENT This file was automatically generated by `generate_dope_interfaces.py`
#undef COMMENT

#ifndef DOPEY_DOPE_SIZES_H
#define DOPEY_DOPE_SIZES_H

#define DOPEY_DOPE_BASE_SIZE 104
#define DOPEY_DOPE_PER_DIM_SIZE 24
#define DOPEY_DOPE_MAX_RANK 3

#endif

#undef FILE_COMMENT
