! DO NOT EDIT THIS FILE DIRECTLY!
! This file was automatically generated by `generate_dope_interfaces.py`

#ifndef DOPEY_NOT_INCLUDED_DIRECTLY
#error "dope_generated_fortran_interfaces.h should not be included directly"
#endif

module procedure :: make_dope_1d_c_int
module procedure :: make_dope_2d_c_int
module procedure :: make_dope_3d_c_int
module procedure :: make_dope_1d_c_float
module procedure :: make_dope_2d_c_float
module procedure :: make_dope_3d_c_float
module procedure :: make_dope_1d_c_double
module procedure :: make_dope_2d_c_double
module procedure :: make_dope_3d_c_double
module procedure :: make_dope_1d_c_bool
module procedure :: make_dope_2d_c_bool
module procedure :: make_dope_3d_c_bool
