! DO NOT EDIT THIS FILE DIRECTLY!
! This file was automatically generated by `generate_dope_interfaces.py`

function make_dope_1d_c_int(a) result(retval)
  use, intrinsic :: iso_c_binding
  implicit none
  integer(c_int), dimension(:), intent(in), target :: a
  type(dope) :: retval
  integer(c_int), dimension(:), pointer :: p
  
  interface
    subroutine make_dope_1d_int(d,a) bind(c)
      use, intrinsic :: iso_c_binding
      import dope
      implicit none
      type(dope), intent(out) :: d
      integer(c_int), dimension(:), pointer, intent(in) :: a
    end subroutine
  end interface
  
  p => a
  call make_dope_1d_int(retval,p)
end function

function make_dope_2d_c_int(a) result(retval)
  use, intrinsic :: iso_c_binding
  implicit none
  integer(c_int), dimension(:,:), intent(in), target :: a
  type(dope) :: retval
  integer(c_int), dimension(:,:), pointer :: p
  
  interface
    subroutine make_dope_2d_int(d,a) bind(c)
      use, intrinsic :: iso_c_binding
      import dope
      implicit none
      type(dope), intent(out) :: d
      integer(c_int), dimension(:,:), pointer, intent(in) :: a
    end subroutine
  end interface
  
  p => a
  call make_dope_2d_int(retval,p)
end function

function make_dope_3d_c_int(a) result(retval)
  use, intrinsic :: iso_c_binding
  implicit none
  integer(c_int), dimension(:,:,:), intent(in), target :: a
  type(dope) :: retval
  integer(c_int), dimension(:,:,:), pointer :: p
  
  interface
    subroutine make_dope_3d_int(d,a) bind(c)
      use, intrinsic :: iso_c_binding
      import dope
      implicit none
      type(dope), intent(out) :: d
      integer(c_int), dimension(:,:,:), pointer, intent(in) :: a
    end subroutine
  end interface
  
  p => a
  call make_dope_3d_int(retval,p)
end function

function make_dope_1d_c_float(a) result(retval)
  use, intrinsic :: iso_c_binding
  implicit none
  real(c_float), dimension(:), intent(in), target :: a
  type(dope) :: retval
  real(c_float), dimension(:), pointer :: p
  
  interface
    subroutine make_dope_1d_float(d,a) bind(c)
      use, intrinsic :: iso_c_binding
      import dope
      implicit none
      type(dope), intent(out) :: d
      real(c_float), dimension(:), pointer, intent(in) :: a
    end subroutine
  end interface
  
  p => a
  call make_dope_1d_float(retval,p)
end function

function make_dope_2d_c_float(a) result(retval)
  use, intrinsic :: iso_c_binding
  implicit none
  real(c_float), dimension(:,:), intent(in), target :: a
  type(dope) :: retval
  real(c_float), dimension(:,:), pointer :: p
  
  interface
    subroutine make_dope_2d_float(d,a) bind(c)
      use, intrinsic :: iso_c_binding
      import dope
      implicit none
      type(dope), intent(out) :: d
      real(c_float), dimension(:,:), pointer, intent(in) :: a
    end subroutine
  end interface
  
  p => a
  call make_dope_2d_float(retval,p)
end function

function make_dope_3d_c_float(a) result(retval)
  use, intrinsic :: iso_c_binding
  implicit none
  real(c_float), dimension(:,:,:), intent(in), target :: a
  type(dope) :: retval
  real(c_float), dimension(:,:,:), pointer :: p
  
  interface
    subroutine make_dope_3d_float(d,a) bind(c)
      use, intrinsic :: iso_c_binding
      import dope
      implicit none
      type(dope), intent(out) :: d
      real(c_float), dimension(:,:,:), pointer, intent(in) :: a
    end subroutine
  end interface
  
  p => a
  call make_dope_3d_float(retval,p)
end function

function make_dope_1d_c_double(a) result(retval)
  use, intrinsic :: iso_c_binding
  implicit none
  real(c_double), dimension(:), intent(in), target :: a
  type(dope) :: retval
  real(c_double), dimension(:), pointer :: p
  
  interface
    subroutine make_dope_1d_double(d,a) bind(c)
      use, intrinsic :: iso_c_binding
      import dope
      implicit none
      type(dope), intent(out) :: d
      real(c_double), dimension(:), pointer, intent(in) :: a
    end subroutine
  end interface
  
  p => a
  call make_dope_1d_double(retval,p)
end function

function make_dope_2d_c_double(a) result(retval)
  use, intrinsic :: iso_c_binding
  implicit none
  real(c_double), dimension(:,:), intent(in), target :: a
  type(dope) :: retval
  real(c_double), dimension(:,:), pointer :: p
  
  interface
    subroutine make_dope_2d_double(d,a) bind(c)
      use, intrinsic :: iso_c_binding
      import dope
      implicit none
      type(dope), intent(out) :: d
      real(c_double), dimension(:,:), pointer, intent(in) :: a
    end subroutine
  end interface
  
  p => a
  call make_dope_2d_double(retval,p)
end function

function make_dope_3d_c_double(a) result(retval)
  use, intrinsic :: iso_c_binding
  implicit none
  real(c_double), dimension(:,:,:), intent(in), target :: a
  type(dope) :: retval
  real(c_double), dimension(:,:,:), pointer :: p
  
  interface
    subroutine make_dope_3d_double(d,a) bind(c)
      use, intrinsic :: iso_c_binding
      import dope
      implicit none
      type(dope), intent(out) :: d
      real(c_double), dimension(:,:,:), pointer, intent(in) :: a
    end subroutine
  end interface
  
  p => a
  call make_dope_3d_double(retval,p)
end function

function make_dope_1d_c_bool(a) result(retval)
  use, intrinsic :: iso_c_binding
  implicit none
  logical(c_bool), dimension(:), intent(in), target :: a
  type(dope) :: retval
  logical(c_bool), dimension(:), pointer :: p
  
  interface
    subroutine make_dope_1d_bool(d,a) bind(c)
      use, intrinsic :: iso_c_binding
      import dope
      implicit none
      type(dope), intent(out) :: d
      logical(c_bool), dimension(:), pointer, intent(in) :: a
    end subroutine
  end interface
  
  p => a
  call make_dope_1d_bool(retval,p)
end function

function make_dope_2d_c_bool(a) result(retval)
  use, intrinsic :: iso_c_binding
  implicit none
  logical(c_bool), dimension(:,:), intent(in), target :: a
  type(dope) :: retval
  logical(c_bool), dimension(:,:), pointer :: p
  
  interface
    subroutine make_dope_2d_bool(d,a) bind(c)
      use, intrinsic :: iso_c_binding
      import dope
      implicit none
      type(dope), intent(out) :: d
      logical(c_bool), dimension(:,:), pointer, intent(in) :: a
    end subroutine
  end interface
  
  p => a
  call make_dope_2d_bool(retval,p)
end function

function make_dope_3d_c_bool(a) result(retval)
  use, intrinsic :: iso_c_binding
  implicit none
  logical(c_bool), dimension(:,:,:), intent(in), target :: a
  type(dope) :: retval
  logical(c_bool), dimension(:,:,:), pointer :: p
  
  interface
    subroutine make_dope_3d_bool(d,a) bind(c)
      use, intrinsic :: iso_c_binding
      import dope
      implicit none
      type(dope), intent(out) :: d
      logical(c_bool), dimension(:,:,:), pointer, intent(in) :: a
    end subroutine
  end interface
  
  p => a
  call make_dope_3d_bool(retval,p)
end function

