#define COMMENT DO NOT EDIT THIS FILE DIRECTLY!
#undef COMMENT
#define COMMENT This file was automatically generated by `generate_dope_interfaces.py`
#undef COMMENT

#ifndef DOPEY_NOT_INCLUDED_DIRECTLY
#error "dope_generated_sizes.h should not be included directly"
#endif

#ifndef DOPEY_DOPE_SIZES_H
#define DOPEY_DOPE_SIZES_H

#define DOPEY_DOPE_MAX_RANK 3

#endif
